# configs/pax5_logreg.yaml
architecture: logreg
tf: PAX5

preprocess_data_dir: /home/mcb/share/datasets-li/eric_neda_connor_comp561
pred_struct_data_dir: /home/mcb/share/datasets-li/eric_neda_connor_comp561/PAX5/bigwig_processed
#pwm_file: /home/mcb/share/datasets-li/eric_neda_connor_comp561/tf-binding/factorbookMotifPwm.txt
pred_struct_features: []


batch_size: 32
use_probs: false
use_seq: true
