architecture: svm
tf: PAX5
batch_size: 32
use_probs: false
preprocess_data_dir: /home/mcb/share/datasets-li/eric_neda_connor_comp561/PAX5
pred_struct_data_dir: /home/mcb/share/datasets-li/eric_neda_connor_comp561
mgw_file_name: hg19.MGW.wig.bw
prot_file_name: hg19.ProT.wig.bw
roll_file_name: hg19.OC2.wig.bw
helt_file_name: hg19.HelT.wig.bw
use_mgws: true
